// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// Use a safe fallback type to satisfy lint rules until typegen is run.
type Env = Record<string, unknown>;
